apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
 name: dk8s-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create"]
