apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kubemarks-rb
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kubemarks-role
subjects:
  - kind: ServiceAccount
    name: kubemarks
